export const CLUB_BUYERS = [
  {
    id: "tipusian",
    minClubLevel: 1,
    name: "Типусиан",
    shortName: "Т",
    role: "Хозяин стола",
    prefers: "tabakko",
    tolerance: 0.72,
    patience: 2,
    opening: [0.82, 0.94],
    amount: [1, 3],
    minQualityRank: 0,
    line: "Свежий товар вижу сразу. Показывай партию.",
    dealLine: "Чисто сработано. Забираю.",
    rejectLine: "Не разгоняй цену. Здесь умеют считать.",
    accent: "cyan",
    portrait: "/assets/characters/club-dealer.png",
  },
  {
    id: "margo",
    minClubLevel: 1,
    name: "Марго Ноль",
    shortName: "М",
    role: "Бармен",
    prefers: "greenTomato",
    tolerance: 0.62,
    patience: 3,
    opening: [0.76, 0.9],
    amount: [1, 3],
    minQualityRank: 0,
    line: "Мне нужна яркая партия для ночной стойки.",
    dealLine: "Подойдёт. Сегодня это разойдётся быстро.",
    rejectLine: "Красиво говоришь, но касса у меня одна.",
    accent: "pink",
    portrait: "/assets/characters/club-buyers/margo-zero.png",
  },
  {
    id: "rax",
    minClubLevel: 2,
    name: "Рэкс-12",
    shortName: "R",
    role: "Курьер",
    prefers: "kokaNova",
    tolerance: 0.78,
    patience: 1,
    opening: [0.9, 1.03],
    amount: [1, 2],
    minQualityRank: 1,
    line: "Мне надо быстро. Хорошая партия — хорошие деньги.",
    dealLine: "Сошлись. Груз уже ждут на другом конце района.",
    rejectLine: "У меня нет времени ходить по кругу.",
    accent: "orange",
    portrait: "/assets/characters/club-buyers/rax-12.png",
  },
  {
    id: "vespa",
    minClubLevel: 3,
    name: "Веспа",
    shortName: "V",
    role: "Коллекционер",
    prefers: "kokaNova",
    tolerance: 0.88,
    patience: 2,
    opening: [0.88, 1.02],
    amount: [1, 2],
    minQualityRank: 2,
    line: "Обычные партии меня не интересуют. Покажи лучшее.",
    dealLine: "Вот это уже достойно моей коллекции.",
    rejectLine: "Редкость не делает любую цену разумной.",
    accent: "violet",
    portrait: "/assets/characters/club-buyers/vespa.png",
  },
  {
    id: "uncle-bit",
    minClubLevel: 1,
    name: "Дядя Бит",
    shortName: "Б",
    role: "Завсегдатай",
    prefers: "tabakko",
    tolerance: 0.55,
    patience: 4,
    opening: [0.68, 0.82],
    amount: [2, 4],
    minQualityRank: 0,
    line: "Я беру объёмом. Дай нормальную цену — и всё уйдёт.",
    dealLine: "По рукам. Объёмом ты всё равно выиграл.",
    rejectLine: "Не-не. За такие деньги я лучше подожду.",
    accent: "green",
    portrait: "/assets/characters/club-buyers/uncle-bit.png",
  },
  {
    id: "luna",
    minClubLevel: 2,
    name: "Луна-3",
    shortName: "Л",
    role: "Музыкант",
    prefers: "greenTomato",
    tolerance: 0.74,
    patience: 2,
    opening: [0.8, 0.96],
    amount: [1, 3],
    minQualityRank: 1,
    line: "Мне нужен вкус, который не потеряется после третьего трека.",
    dealLine: "Да. Именно такой звук я и искала.",
    rejectLine: "Музыка громкая, но цену я слышу отлично.",
    accent: "blue",
    portrait: "/assets/characters/club-buyers/luna-3.png",
  },
  {
    id: "broker",
    minClubLevel: 1,
    name: "Серый Брокер",
    shortName: "С",
    role: "Перекупщик",
    prefers: null,
    tolerance: 0.46,
    patience: 3,
    opening: [0.62, 0.78],
    amount: [2, 4],
    minQualityRank: 0,
    line: "Заберу всё сейчас. Но свою маржу оставь мне.",
    dealLine: "Сойдёт. Дальше это уже моя забота.",
    rejectLine: "С такой наценкой перекупать нечего.",
    accent: "gray",
    portrait: "/assets/characters/club-buyers/gray-broker.png",
  },
  {
    id: "oracle",
    minClubLevel: 5,
    name: "Оракул",
    shortName: "О",
    role: "Редкий гость",
    prefers: null,
    tolerance: 0.92,
    patience: 1,
    opening: [0.96, 1.1],
    amount: [1, 2],
    minQualityRank: 2,
    line: "Сегодня цену решает не рынок. Покажи лучшее.",
    dealLine: "Цена верная. Значит, встреча была не случайной.",
    rejectLine: "Ты увидел слишком много знаков в одной монете.",
    accent: "gold",
    portrait: "/assets/characters/club-buyers/oracle.png",
  },
  {
    id: "kira-volt",
    minClubLevel: 2,
    name: "Кира Вольт",
    shortName: "К",
    role: "Светотехник",
    prefers: "greenTomato",
    tolerance: 0.7,
    patience: 2,
    opening: [0.79, 0.95],
    amount: [1, 3],
    minQualityRank: 1,
    line: "Нужна партия, которая переживёт всю ночную смену.",
    dealLine: "Работает. Забираю до включения света.",
    rejectLine: "Не коротни сделку слишком высокой ценой.",
    accent: "electric",
    portrait: "/assets/characters/club-buyers/kira-volt.png",
  },
  {
    id: "nox",
    minClubLevel: 1,
    name: "Нокс",
    shortName: "Н",
    role: "Ночной повар",
    prefers: "tabakko",
    tolerance: 0.66,
    patience: 3,
    opening: [0.74, 0.91],
    amount: [2, 4],
    minQualityRank: 0,
    line: "Мне важен стабильный вкус. Без сюрпризов.",
    dealLine: "Ровная партия. На кухне оценят.",
    rejectLine: "Я плачу за вкус, а не за легенду вокруг него.",
    accent: "lime",
    portrait: "/assets/characters/club-buyers/nox.png",
  },
  {
    id: "madam-flux",
    minClubLevel: 3,
    name: "Мадам Флюкс",
    shortName: "Ф",
    role: "Промоутер",
    prefers: "kokaNova",
    tolerance: 0.83,
    patience: 2,
    opening: [0.86, 1.04],
    amount: [1, 3],
    minQualityRank: 2,
    line: "Мне нужен товар, который запомнят после вечеринки.",
    dealLine: "Эта партия получит лучший стол.",
    rejectLine: "Публика щедрая, но я не бездонная.",
    accent: "magenta",
    portrait: "/assets/characters/club-buyers/madam-flux.png",
  },
  {
    id: "bongo",
    minClubLevel: 1,
    name: "Бонго",
    shortName: "Б",
    role: "Уличный артист",
    prefers: "greenTomato",
    tolerance: 0.58,
    patience: 4,
    opening: [0.7, 0.86],
    amount: [1, 4],
    minQualityRank: 0,
    line: "Давай без официоза. Товар сюда, монеты туда.",
    dealLine: "Вот теперь звучим в одном ритме.",
    rejectLine: "Ритм сбился. Давай ближе к земле.",
    accent: "sunset",
    portrait: "/assets/characters/club-buyers/bongo.png",
  },
  {
    id: "pix",
    minClubLevel: 2,
    name: "Пикс",
    shortName: "П",
    role: "Стример",
    prefers: null,
    tolerance: 0.76,
    patience: 2,
    opening: [0.82, 0.98],
    amount: [1, 2],
    minQualityRank: 1,
    line: "Мне нужна красивая партия. Зрители замечают детали.",
    dealLine: "Отличный кадр. И отличная сделка.",
    rejectLine: "Чат уже пишет, что цена перегрета.",
    accent: "aqua",
    portrait: "/assets/characters/club-buyers/pix.png",
  },
  {
    id: "quiet-tai",
    minClubLevel: 2,
    name: "Тихий Тай",
    shortName: "Т",
    role: "Посредник",
    prefers: "tabakko",
    tolerance: 0.8,
    patience: 1,
    opening: [0.88, 1.02],
    amount: [2, 3],
    minQualityRank: 1,
    line: "У меня одна попытка и один маршрут. Не подведи.",
    dealLine: "Без лишних слов. Договорились.",
    rejectLine: "Маршрут закрыт. Я ухожу.",
    accent: "ice",
    portrait: "/assets/characters/club-buyers/quiet-tai.png",
  },
];

function randomBetween(min, max) {
  return min + Math.random() * (max - min);
}

export function createClubLineup(count = 3, excludedBuyerIds = [], clubLevel = 1) {
  const excluded = new Set(excludedBuyerIds);
  const safeLevel = Math.max(1, Math.floor(Number(clubLevel) || 1));
  const levelPool = CLUB_BUYERS.filter(
    (buyer) => (buyer.minClubLevel || 1) <= safeLevel,
  );
  const freshPool = levelPool.filter((buyer) => !excluded.has(buyer.id));
  const source = freshPool.length >= count ? freshPool : levelPool;
  const pool = [...source].sort(() => Math.random() - 0.5).slice(0, count);

  return pool.map((buyer) => ({
    ...buyer,
    openingFactor: Number(
      randomBetween(buyer.opening[0], buyer.opening[1]).toFixed(2),
    ),
    offerFactor: Number(
      randomBetween(buyer.opening[0], buyer.opening[1]).toFixed(2),
    ),
    patienceLeft: buyer.patience,
    status: "active",
    message: buyer.line,
    replaceAt: 0,
    exitReason: null,
  }));
}
