export const G_COIN_PACKAGES = Object.freeze([
  {
    id: "starter",
    title: "Стартовый запас",
    subtitle: "Для первых ускорений",
    stars: 10,
    coins: 100,
    baseCoins: 100,
    badge: "НОВИЧКУ",
    benefit: "СТАРТОВЫЙ ПАКЕТ",
    visualCoins: 1,
    theme: "starter",
  },
  {
    id: "street",
    title: "Уличный набор",
    subtitle: "Хватит надолго",
    stars: 30,
    coins: 330,
    baseCoins: 300,
    badge: "ПОПУЛЯРНО",
    benefit: "+10% ВЫГОДЫ",
    visualCoins: 3,
    theme: "street",
  },
  {
    id: "grower",
    title: "Запас гровера",
    subtitle: "Для активной игры",
    stars: 75,
    coins: 900,
    baseCoins: 750,
    badge: "ВЫГОДНО",
    benefit: "+20% ВЫГОДЫ",
    visualCoins: 5,
    theme: "grower",
  },
  {
    id: "boss",
    title: "Банк района",
    subtitle: "Максимальный пакет",
    stars: 150,
    coins: 1950,
    baseCoins: 1500,
    badge: "МАКСИМУМ",
    benefit: "+30% ВЫГОДЫ",
    visualCoins: 9,
    theme: "boss",
  },
]);

export const COIN_EXCHANGE_PACKAGES = Object.freeze([
  {
    id: "coin-pocket",
    title: "Карман мелочи",
    subtitle: "На семена и расходники",
    gCost: 15,
    coins: 120,
    badge: "НОВИЧКУ",
    benefit: "СТАРТОВЫЙ ПАКЕТ",
    visualCoins: 1,
    theme: "pocket",
  },
  {
    id: "coin-stash",
    title: "Уличный запас",
    subtitle: "Для лавки и второго ведра",
    gCost: 45,
    coins: 400,
    badge: "ПОПУЛЯРНО",
    benefit: "+10% ВЫГОДЫ",
    visualCoins: 3,
    theme: "stash",
  },
  {
    id: "coin-crate",
    title: "Ящик налички",
    subtitle: "Большая закупка без ожидания",
    gCost: 110,
    coins: 1100,
    badge: "ВЫГОДНО",
    benefit: "+25% ВЫГОДЫ",
    visualCoins: 5,
    theme: "crate",
  },
  {
    id: "coin-vault",
    title: "Касса района",
    subtitle: "Серьёзный запас на развитие",
    gCost: 260,
    coins: 3000,
    badge: "МАКСИМУМ",
    benefit: "+40% ВЫГОДЫ",
    visualCoins: 9,
    theme: "vault",
  },
]);

export function formatStoreNumber(value) {
  return new Intl.NumberFormat("ru-RU").format(
    Math.max(0, Math.floor(Number(value) || 0)),
  );
}
