const quest = (
  id,
  chapter,
  title,
  description,
  objective,
  coins,
  trust,
  icon,
  previousQuestId = null,
  bonus = null,
) => ({
  id,
  chapter,
  title,
  description,
  objective,
  reward: { coins, trust, ...(bonus || {}) },
  icon,
  previousQuestId,
});

export const MARIA_CHAPTERS = [
  {
    id: 1,
    title: "Чужой двор",
    subtitle: "Освой первый цикл и докажи, что умеешь доводить дело до конца.",
    reward: {
      icon: "🪣",
      title: "Второе ведро Марии",
      description: "Мария отдаст старое рабочее ведро бесплатно. На плантации появится второй одновременный цикл.",
      accent: "БЕСПЛАТНОЕ РАСШИРЕНИЕ",
    },
  },
  {
    id: 2,
    title: "Кислая линия",
    subtitle: "Разгони оборот Кислоплода и научись не продавать весь запас сразу.",
    reward: {
      icon: "🟢",
      title: "Запас Кислоплода",
      description: "Два семени в подарок и новый круг поручений на торговлю.",
      accent: "2 СЕМЕНИ",
    },
  },
  {
    id: 3,
    title: "Закрытая поставка",
    subtitle: "Освой дорогую культуру и заслужи право расширить плантацию ещё раз.",
    reward: {
      icon: "🪣",
      title: "Разрешение на третье ведро",
      description: "Мария освободит место. Установить ведро можно за 420 обычных монет.",
      accent: "НОВОЕ МЕСТО",
    },
  },
  {
    id: 4,
    title: "Работа на качество",
    subtitle: "Перейди от случайного урожая к стабильным дорогим партиям.",
    reward: {
      icon: "🧪",
      title: "Смесь и четвёртое место",
      description: "Одна смесь Марии сразу и право установить четвёртое ведро за 900 монет.",
      accent: "ФИНАЛЬНОЕ РАСШИРЕНИЕ",
    },
  },
  {
    id: 5,
    title: "Имя на Grow Street",
    subtitle: "Собери редкую коллекцию и стань поставщиком, которого знает весь район.",
    reward: {
      icon: "🔑",
      title: "Ключ от старого лифта",
      description: "Финал верхней плантации и вход в будущую подземную главу.",
      accent: "СЮЖЕТНАЯ НАГРАДА",
    },
  },
];

export const MARIA_QUESTS = [
  quest("maria-tabakko-delivery",1,"Первая связка","Принеси Марии три листа Табакко. Это твой пропуск в район.",{type:"deliver",itemId:"tabakko",amount:3},12,25,"🌿"),
  quest("maria-first-watering",1,"Не лей бездумно","Полей растение во время активной стадии роста.",{type:"care-use",careType:"water",amount:1},8,25,"💦","maria-tabakko-delivery"),
  quest("maria-tabakko-stock",1,"Запас на вечер","Собери и передай ещё четыре листа Табакко.",{type:"deliver",itemId:"tabakko",amount:4},10,8,"▦","maria-first-watering"),
  quest("maria-tabakko-harvest-6",1,"Руки запомнили","Собери суммарно шесть листов Табакко. Марии нужен не случайный успех, а повторяемый цикл.",{type:"harvest-count",itemId:"tabakko",amount:6},10,5,"↻","maria-tabakko-stock"),
  quest("maria-tabakko-club",1,"Первый выход","Продай в клубе три листа Табакко.",{type:"club-sale",itemId:"tabakko",amount:3},12,8,"♣","maria-tabakko-harvest-6"),
  quest("maria-club-rep-20",1,"Чтобы запомнили","Подними репутацию клуба до 20.",{type:"club-reputation",amount:20},10,6,"✶","maria-tabakko-club"),
  quest("maria-tabakko-good",1,"Не просто лист","Получи Табакко качеством не ниже хорошего.",{type:"quality-rank",itemId:"tabakko",rank:1,amount:1},14,8,"◆","maria-club-rep-20"),
  quest("maria-water-three",1,"Ровная рука","Используй полив суммарно три раза. После этого Мария отдаст тебе второе ведро.",{type:"care-use",careType:"water",amount:3},8,5,"🪣","maria-tabakko-good",{slotUnlock:2}),

  quest("maria-kisloplod-seed",2,"Кислая закупка","Купи первое семя Кислоплода.",{type:"own-seed",itemId:"greenTomato",amount:1},8,5,"🟢","maria-water-three"),
  quest("maria-kisloplod-delivery",2,"Проба урожая","Принеси один Кислоплод.",{type:"deliver",itemId:"greenTomato",amount:1},14,7,"◉","maria-kisloplod-seed"),
  quest("maria-kisloplod-harvest-4",2,"Кислый конвейер","Собери суммарно четыре Кислоплода. Один удачный плод ещё ничего не значит.",{type:"harvest-count",itemId:"greenTomato",amount:4},16,5,"↻","maria-kisloplod-delivery"),
  quest("maria-kisloplod-club",2,"Кислый спрос","Продай в клубе два Кислоплода.",{type:"club-sale",itemId:"greenTomato",amount:2},18,7,"♣","maria-kisloplod-harvest-4"),
  quest("maria-club-rep-45",2,"Нормальный разговор","Подними репутацию клуба до 45.",{type:"club-reputation",amount:45},12,5,"✶","maria-kisloplod-club"),
  quest("maria-kisloplod-good",2,"Без кислой мины","Получи Кислоплод качеством не ниже хорошего.",{type:"quality-rank",itemId:"greenTomato",rank:1,amount:1},18,7,"◆","maria-club-rep-45"),
  quest("maria-tabakko-sale-8",2,"Постоянный клиент","Продай клубу суммарно восемь листов Табакко.",{type:"club-sale",itemId:"tabakko",amount:8},14,5,"▣","maria-kisloplod-good"),
  quest("maria-kisloplod-delivery-3",2,"Партия для кухни","Передай Марии три Кислоплода.",{type:"deliver",itemId:"greenTomato",amount:3},22,8,"◉","maria-tabakko-sale-8"),
  quest("maria-club-rep-75",2,"Своё место","Подними репутацию клуба до 75.",{type:"club-reputation",amount:75},16,6,"★","maria-kisloplod-delivery-3",{seeds:{greenTomato:2}}),

  quest("maria-koka-seed",3,"Закрытый пакет","Купи первое семя Кока Новы.",{type:"own-seed",itemId:"kokaNova",amount:1},12,5,"🍃","maria-club-rep-75"),
  quest("maria-koka-delivery",3,"Проверка Марии","Принеси один урожай Кока Новы.",{type:"deliver",itemId:"kokaNova",amount:1},24,8,"✦","maria-koka-seed"),
  quest("maria-koka-harvest-4",3,"Красная серия","Собери четыре Кока Новы суммарно. Дорогая культура должна работать серией.",{type:"harvest-count",itemId:"kokaNova",amount:4},26,6,"↻","maria-koka-delivery"),
  quest("maria-koka-club",3,"Дорогой стол","Продай в клубе две Кока Новы.",{type:"club-sale",itemId:"kokaNova",amount:2},30,8,"♣","maria-koka-harvest-4"),
  quest("maria-club-rep-110",3,"Тебя уже знают","Подними репутацию клуба до 110.",{type:"club-reputation",amount:110},18,6,"✶","maria-koka-club"),
  quest("maria-koka-good",3,"Чистая партия","Получи Кока Нову качеством не ниже хорошего.",{type:"quality-rank",itemId:"kokaNova",rank:1,amount:1},28,8,"◆","maria-club-rep-110"),
  quest("maria-kisloplod-sale-6",3,"Держи ассортимент","Продай клубу суммарно шесть Кислоплодов.",{type:"club-sale",itemId:"greenTomato",amount:6},22,6,"▦","maria-koka-good"),
  quest("maria-koka-delivery-3",3,"Три красных листа","Передай Марии три Кока Новы.",{type:"deliver",itemId:"kokaNova",amount:3},36,8,"🍃","maria-kisloplod-sale-6"),
  quest("maria-club-rep-150",3,"Поставщик","Подними репутацию клуба до 150. После этого Мария разрешит поставить третье ведро.",{type:"club-reputation",amount:150},24,7,"🪣","maria-koka-delivery-3",{slotUnlock:3}),

  quest("maria-nutrition-own",4,"Питание, не магия","Купи питательный раствор.",{type:"own-tool",itemId:"nutrition",amount:1},10,4,"🌿","maria-club-rep-150"),
  quest("maria-nutrition-care",4,"Работа на качество","Используй питательный раствор во время роста.",{type:"care-use",careType:"nutrition",amount:1},18,7,"🧪","maria-nutrition-own"),
  quest("maria-excellent-any",4,"Отличная партия","Получи любую культуру отличного качества.",{type:"quality-any",rank:2,amount:1},40,9,"✦","maria-nutrition-care"),
  quest("maria-excellent-three",4,"Не случайность","Собери три урожая отличного качества или выше.",{type:"quality-count",rank:2,amount:3},34,7,"✦","maria-excellent-any"),
  quest("maria-club-rep-210",4,"Торг без суеты","Подними репутацию клуба до 210.",{type:"club-reputation",amount:210},24,7,"♣","maria-excellent-three"),
  quest("maria-koka-sale-5",4,"Пять дорогих сделок","Продай клубу суммарно пять Кока Нов.",{type:"club-sale",itemId:"kokaNova",amount:5},42,8,"▣","maria-club-rep-210"),
  quest("maria-water-eight",4,"Режим","Используй полив суммарно восемь раз.",{type:"care-use",careType:"water",amount:8},14,5,"≈","maria-koka-sale-5"),
  quest("maria-nutrition-three",4,"Без случайностей","Используй питательный раствор три раза.",{type:"care-use",careType:"nutrition",amount:3},28,7,"🌿","maria-water-eight"),
  quest("maria-club-rep-280",4,"Хорошая фамилия","Подними репутацию клуба до 280. Мария откроет четвёртое место и отдаст одну смесь.",{type:"club-reputation",amount:280},30,8,"🪣","maria-nutrition-three",{care:{mariaMix:1},slotUnlock:4}),

  quest("maria-mix-own",5,"Секретный флакон","Получи или купи смесь Марии Ивановны.",{type:"own-tool",itemId:"mariaMix",amount:1},14,4,"🧪","maria-club-rep-280"),
  quest("maria-mix-use",5,"Без свидетелей","Используй смесь Марии во время роста.",{type:"care-use",careType:"mariaMix",amount:1},20,7,"✧","maria-mix-own"),
  quest("maria-rare-discovery",5,"Редкая отметка","Открой хотя бы один редкий урожай.",{type:"rare-discovery",amount:1},80,12,"★","maria-mix-use"),
  quest("maria-rare-two",5,"Не единичный случай","Собери два редких урожая суммарно.",{type:"quality-count",rank:3,amount:2},70,10,"✧","maria-rare-discovery"),
  quest("maria-club-rep-350",5,"Свой поставщик","Подними репутацию клуба до 350.",{type:"club-reputation",amount:350},36,8,"♣","maria-rare-two"),
  quest("maria-all-sales",5,"Полный прилавок","Продай в клубе не меньше пяти единиц каждой культуры.",{type:"club-sale-each",amount:5},70,12,"▦","maria-club-rep-350"),
  quest("maria-excellent-koka",5,"Лучший лист","Получи Кока Нову отличного качества.",{type:"quality-rank",itemId:"kokaNova",rank:2,amount:1},60,12,"✦","maria-all-sales"),
  quest("maria-total-harvest-45",5,"Сорок пять сборов","Собери суммарно 45 единиц урожая. Район должен увидеть, что это уже настоящее производство.",{type:"harvest-total",amount:45},54,10,"↻","maria-excellent-koka"),
  quest("maria-club-rep-420",5,"Имя на районе","Подними репутацию клуба до 420.",{type:"club-reputation",amount:420},50,15,"★","maria-total-harvest-45"),
  quest("maria-final-delivery",5,"Ключ от лифта","Принеси Марии по три единицы каждой культуры. Она покажет, что спрятано под домом.",{type:"deliver-set",items:{tabakko:3,greenTomato:3,kokaNova:3},amount:9},110,25,"🔑","maria-club-rep-420"),
];

export const DISTRICT_BULLETINS = [
  { title: "У клуба сменился бармен", text: "Новый бармен любит качественный Табакко и хуже переносит наглые цены. Сегодня лучше закрывать ровные сделки." },
  { title: "У Зорика задержалась машина", text: "Редкие поставки приходят не по расписанию. Проверяй лавку после обновления — оснащение исчезает быстрее семян." },
  { title: "Кто-то слышал лифт", text: "Ночью под домом Марии снова гудел старый механизм. Сама она говорит, что это трубы. Никто ей не верит." },
  { title: "Кислоплод вошёл в моду", text: "В клубе его мешают с ледяной водой. Покупатели готовы брать больше, но только хорошее качество." },
  { title: "Проверка на районе", text: "Типусиан просит не носить весь урожай одному покупателю. Когда один стол знает твой запас, торг становится хуже." },
  { title: "Мария закрыла окно", text: "Значит, снова варит свою смесь. Зорик клянётся, что ничего не знает, но уже освободил место на полке." },
  { title: "Старое правило Grow Street", text: "Быстрые деньги делают тебя заметным. Хорошие сделки делают тебя своим. Репутация открывает больше, чем монеты." },
  { title: "Пропал грузчик", text: "Последний раз его видели возле закрытого лифта. На стене осталась только надпись: «не выращивайте это наверху»." },
];
